### ISSUE TITLE
Several things were removed in 0.1.1 without notice

### ISSUE THREAD

**Issue by marcosnils** [monzo/response#116]
Just downloaded and install the latest version of `response` and noticed that several things like workflows, pagerduty and statuspage are missing. After re-checking the latest release-notes (https://github.com/monzo/response/releases/tag/release-0.1.1) and not seeing anything about this I found this commit that refactors this functionality 81e389e091fea49f1af143ebbeb2aa2ebd77c3b4

I guess the missing pieces here are: 

- Update the release to state that those features were removed
- Create an issue to discuss about how this would be implemented so others can contribute? It's sad to see those features going all of the sudden. Wish the transition was smoother without actually having to lose them at all :cry:

**Comment by milesbxf** [comment]
Hi @marcosnils - really sorry about this, I'll update the release notes now.

The plan is to introduce these back in but make them entirely optional and customisable by creating a separate `recipes` directory, which would have Python snippets anyone can copy into their own project - I think it'd get too unwieldy otherwise.

For context, we're under a bit of pressure internally to get some new features out on our private project, and sadly that takes priority, so I can't give you a definite timeframe from when we'll be able to add these all back in - should hopefully be a week or two though. I'll create the issue too.

**Comment by marcosnils** [comment]
> For context, we're under a bit of pressure internally to get some new features out on our private project, and sadly that takes priority, so I can't give you a definite timeframe from when we'll be able to add these all back in - should hopefully be a week or two though. I'll create the issue too.

That's totally understandable and it makes sense. I'm just suggesting to be a bit more organized in the OS project as it's very difficult for users and contributors to follow-up or understand what's happening. 

On a different subject, we had to fork and re-add some part of the functionality that was removed as it was super useful for us.

**Comment by marcosnils** [comment]
I'll close this as the release notes were updated.
