### ISSUE TITLE
Error Occured

### ISSUE THREAD

**Issue by dwarkab** [monzo/response#86]
Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by danpalmer** [comment]
@dwarkab this means that you're either not running the Postgres database, or if you are running it, that it's inaccessible to the application you're trying to connect to it, possibly due to a misconfiguration in Postgres or the application you're trying to connect. I'm afraid this isn't an easy fix, there are many things that could be wrong.

If you're having trouble getting `monzo/response` working, I recommend posting your configuration, and the steps you've taken so far to help us help you.
